/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "/Users/yofoon/Documents/mayf/FE-FACE/node_modules/@vuepress/core/lib/client/components/GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-7757c222",
    path: "/blog/20200414-enqueue-update.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7757c222").then(next)
    },
  },
  {
    name: "v-3112c2a9",
    path: "/blog/20200414-hide-element.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3112c2a9").then(next)
    },
  },
  {
    name: "v-40d09502",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-40d09502").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-fcb09c0e",
    path: "/blog/20200414-react-data-struct.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-fcb09c0e").then(next)
    },
  },
  {
    name: "v-2c3d826d",
    path: "/blog/20200414-react-dom-render.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2c3d826d").then(next)
    },
  },
  {
    name: "v-2b3ba319",
    path: "/blog/20200414-jsx-2-virtual-dom.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2b3ba319").then(next)
    },
  },
  {
    name: "v-37b5d719",
    path: "/blog/20200414-schedule-work.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-37b5d719").then(next)
    },
  },
  {
    name: "v-0f22d593",
    path: "/blog/20200414-shell-push-git.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0f22d593").then(next)
    },
  },
  {
    name: "v-3852c299",
    path: "/blog/20200414-expiration-time.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3852c299").then(next)
    },
  },
  {
    name: "v-c7e05b38",
    path: "/knowledge/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c7e05b38").then(next)
    },
  },
  {
    path: "/knowledge/index.html",
    redirect: "/knowledge/"
  },
  {
    name: "v-e836351c",
    path: "/blog/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e836351c").then(next)
    },
  },
  {
    path: "/blog/index.html",
    redirect: "/blog/"
  },
  {
    name: "v-2d45693a",
    path: "/knowledge/WebpackHMR.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2d45693a").then(next)
    },
  },
  {
    name: "v-7ff89cce",
    path: "/knowledge/algorithm.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7ff89cce").then(next)
    },
  },
  {
    name: "v-d08f7442",
    path: "/knowledge/abstract.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d08f7442").then(next)
    },
  },
  {
    name: "v-7a993a79",
    path: "/blog/20200414-intersection-observer.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7a993a79").then(next)
    },
  },
  {
    name: "v-2ae55c39",
    path: "/knowledge/ast.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2ae55c39").then(next)
    },
  },
  {
    name: "v-555bd351",
    path: "/knowledge/book.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-555bd351").then(next)
    },
  },
  {
    name: "v-3f217679",
    path: "/knowledge/cache.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3f217679").then(next)
    },
  },
  {
    name: "v-4dbd18d9",
    path: "/knowledge/babelPlugin.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4dbd18d9").then(next)
    },
  },
  {
    name: "v-e560960e",
    path: "/knowledge/browser.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e560960e").then(next)
    },
  },
  {
    name: "v-2484e966",
    path: "/knowledge/common.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2484e966").then(next)
    },
  },
  {
    name: "v-5e0cccd9",
    path: "/knowledge/cdn.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5e0cccd9").then(next)
    },
  },
  {
    name: "v-91bc43ce",
    path: "/knowledge/css.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-91bc43ce").then(next)
    },
  },
  {
    name: "v-749a42b9",
    path: "/knowledge/devsProxy.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-749a42b9").then(next)
    },
  },
  {
    name: "v-00fa9bd9",
    path: "/knowledge/deepclone.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-00fa9bd9").then(next)
    },
  },
  {
    name: "v-182d8439",
    path: "/knowledge/dom.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-182d8439").then(next)
    },
  },
  {
    name: "v-7c20108e",
    path: "/knowledge/domRender.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7c20108e").then(next)
    },
  },
  {
    name: "v-0dc94419",
    path: "/knowledge/engineering.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0dc94419").then(next)
    },
  },
  {
    name: "v-6f34450e",
    path: "/knowledge/event.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6f34450e").then(next)
    },
  },
  {
    name: "v-147abb0e",
    path: "/knowledge/eventLoop.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-147abb0e").then(next)
    },
  },
  {
    name: "v-266f66d9",
    path: "/knowledge/execute.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-266f66d9").then(next)
    },
  },
  {
    name: "v-f3518f36",
    path: "/knowledge/hoisting.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f3518f36").then(next)
    },
  },
  {
    name: "v-6cfbfeda",
    path: "/knowledge/http.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6cfbfeda").then(next)
    },
  },
  {
    name: "v-79eaae66",
    path: "/knowledge/html.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-79eaae66").then(next)
    },
  },
  {
    name: "v-47cb2ab9",
    path: "/knowledge/fiber.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-47cb2ab9").then(next)
    },
  },
  {
    name: "v-42f01499",
    path: "/knowledge/httpWritten.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-42f01499").then(next)
    },
  },
  {
    name: "v-7163f779",
    path: "/knowledge/http2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7163f779").then(next)
    },
  },
  {
    name: "v-70928519",
    path: "/knowledge/https.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-70928519").then(next)
    },
  },
  {
    name: "v-0adb5af9",
    path: "/knowledge/immutable.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0adb5af9").then(next)
    },
  },
  {
    name: "v-e4b09e4e",
    path: "/knowledge/jsBasic.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e4b09e4e").then(next)
    },
  },
  {
    name: "v-6291f879",
    path: "/knowledge/jsWritten.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6291f879").then(next)
    },
  },
  {
    name: "v-016450d9",
    path: "/knowledge/mechanism.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-016450d9").then(next)
    },
  },
  {
    name: "v-214d67a1",
    path: "/knowledge/memory.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-214d67a1").then(next)
    },
  },
  {
    name: "v-0185f839",
    path: "/knowledge/jsonp.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0185f839").then(next)
    },
  },
  {
    name: "v-4dfa88d7",
    path: "/knowledge/load.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4dfa88d7").then(next)
    },
  },
  {
    name: "v-d88374ce",
    path: "/knowledge/react.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d88374ce").then(next)
    },
  },
  {
    name: "v-0b4cfdde",
    path: "/knowledge/router.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0b4cfdde").then(next)
    },
  },
  {
    name: "v-553f5a0e",
    path: "/knowledge/reactHook.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-553f5a0e").then(next)
    },
  },
  {
    name: "v-121f889f",
    path: "/knowledge/node.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-121f889f").then(next)
    },
  },
  {
    name: "v-7595c25f",
    path: "/knowledge/reactivity.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7595c25f").then(next)
    },
  },
  {
    name: "v-0c1110ba",
    path: "/knowledge/security.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0c1110ba").then(next)
    },
  },
  {
    name: "v-1d661d81",
    path: "/knowledge/string.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1d661d81").then(next)
    },
  },
  {
    name: "v-687108f6",
    path: "/knowledge/setState.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-687108f6").then(next)
    },
  },
  {
    name: "v-686197b9",
    path: "/knowledge/redux.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-686197b9").then(next)
    },
  },
  {
    name: "v-77a343b9",
    path: "/knowledge/vue.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-77a343b9").then(next)
    },
  },
  {
    name: "v-2e4f9896",
    path: "/knowledge/virtualDom.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2e4f9896").then(next)
    },
  },
  {
    name: "v-721afe59",
    path: "/knowledge/tcp.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-721afe59").then(next)
    },
  },
  {
    name: "v-0c278899",
    path: "/knowledge/url.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0c278899").then(next)
    },
  },
  {
    name: "v-5f549bd9",
    path: "/knowledge/webpack.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5f549bd9").then(next)
    },
  },
  {
    name: "v-0c77d239",
    path: "/knowledge/webpackLoader.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0c77d239").then(next)
    },
  },
  {
    name: "v-50fea499",
    path: "/knowledge/webpackMoudle.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-50fea499").then(next)
    },
  },
  {
    name: "v-190c22b9",
    path: "/knowledge/webpackPluginDesign.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-190c22b9").then(next)
    },
  },
  {
    name: "v-a444738e",
    path: "/knowledge/webpackPlugin.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a444738e").then(next)
    },
  },
  {
    path: '*',
    component: GlobalLayout
  }
]